#!/usr/bin/env bash

if [ -z "$MMDAPP" ] ; then
	set -e
	export MMDAPP="$( cd $(dirname "$0")/../../../.. ; pwd )"
	echo "$0: Working in: $MMDAPP"  >&2
	[ -d "$MMDAPP/source" ] || ( echo "ERROR: expecting 'source' directory." >&2 && exit 1 )
fi

if ! type DistroShellContext >/dev/null 2>&1 ; then
	. "$MMDAPP/source/myx/myx.distro-deploy/sh-lib/DistroShellContext.include"
	DistroShellContext --distro-path-auto
fi

Require ListDistroProvides
Require ListProjectProvides

InstallPrepareScript(){
	set -e

	[ -z "$MDSC_DETAIL" ] || echo "> InstallPrepareScript $@" >&2
	# [ -z "$MDSC_DETAIL" ] || printf "| InstallPrepareScript: \n\tSOURCE: $MDSC_SOURCE\n\tCACHED: $MDSC_CACHED\n\tOUTPUT: $MDSC_OUTPUT\n" >&2
	
	local MDSC_PRJ_NAME="${MDSC_PRJ_NAME:-}"
	
	while true ; do
		case "$1" in
			--project)
				shift ; DistroSelectProject MDSC_PRJ_NAME "$1" ; shift
			;;
			*)
				break
			;;
		esac
	done

	if [ -z "$MDSC_PRJ_NAME" ] ; then
		echo "ERROR: InstallPrepareScript: project is not selected!" >&2
		return 1
	fi

	case "$1" in
		--print-files)
			( \
				ListProjectProvides "$MDSC_PRJ_NAME" --merge-sequence --filter-and-cut image-install:exec-update-before ;
				ListProjectProvides "$MDSC_PRJ_NAME" --merge-sequence --filter-and-cut image-install:exec-update-after | tail -r ;
			) \
			| while read -r sourceName scriptPath ; do
				local fileName="$MDSC_SOURCE/$sourceName/$scriptPath"
				if [ ! -f "$fileName" ] ; then
					echo "ERROR: InstallPrepareScript: file is missing: $fileName" >&2; 
					return 1
				fi
				echo "$fileName"
			done
			return 0 
		;;
		--print-script)
			echo "#!/bin/sh"
			echo "#*- 	"
			echo "#*- 	generated at `date -u`"
			echo "#*- 	generated on `hostname`"
			echo "#*- 	generated by `whoami`"
			echo "#*- 	"
			echo "#*- 	generated for $MDSC_PRJ_NAME"
			echo "#*- 	"
			echo "#*- 	contents:"
			
			local fileNames="$( InstallPrepareScript --print-files )"

			echo "$fileNames" \
			| while read -r fileName ; do
				echo "##**--     $fileName"
			done

			echo "#*- 	"
			echo
			echo
			
			echo "$fileNames" \
			| while read -r fileName ; do
				echo "##**--  start, $fileName"
				echo
				cat "$fileName"
				echo
				echo "##**--  end, $fileName"
			done

			echo
			echo
			echo "#*- 	EOF, generated for $MDSC_PRJ_NAME"

			return 0 
		;;
		--to-file)
			shift
			local targetFile="$1"
			if [ -z "$targetFile" ] ; then
				echo "InstallPrepareScript: 'targetFile' argument is required!" >&2 ; return 1
			fi
			
			InstallPrepareScript --print-script > "$targetFile"
			return 0 
		;;
		*)
			echo "ERROR: InstallPrepareScript: invalid option: $1" >&2
			return 1
		;;
	esac
}

case "$0" in
	*/sh-scripts/InstallPrepareScript.fn.sh)
		if [ -z "$1" ] || [ "$1" = "--help" ] ; then
			echo "syntax: InstallPrepareScript.fn.sh <project> --print-files/--print-script" >&2
			echo "syntax: InstallPrepareScript.fn.sh <project> --to-file <targetDirectory>" >&2
			echo "syntax: InstallPrepareScript.fn.sh [--help]" >&2
			if [ "$1" = "--help" ] ; then
				echo "  Examples:" >&2
				echo "    InstallPrepareScript.fn.sh ndm/cloud.knt/setup.host-ndss112r3.ndm9.xyz --print-script" >&2
				echo "    InstallPrepareScript.fn.sh prv/cloud.mel/setup.host-l6b2h1.myx.co.nz --print-files" >&2
				echo "    InstallPrepareScript.fn.sh prv/cloud.mel/setup.host-l6b2h1.myx.co.nz --print-script" >&2
			fi
			exit 1
		fi
		
		InstallPrepareScript "$@"
	;;
esac